manifest:
  remotes:
    - name: nrfconnect
      url-base: https://github.com/nrfconnect

  projects:
    # Nordic binary libraries (SDC, MPSL) and headers
    # No board_root in its module.yml - safe to include
    - name: nrfxlib
      remote: nrfconnect
      revision: d4ce5fe1a7d8af29bc01a4e1ddf5540ef65b6a3b  # v3.4.0
      repo-path: sdk-nrfxlib
      path: nrfxlib

  self:
    path: zmk-softdevice-controller
