CONFIG_BT_LL_SW_SPLIT=n
CONFIG_ZMK_BT_LL_SOFTDEVICE=y

# 2M PHY for lower latency and reduced radio on-time
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_PHY_UPDATE=y
CONFIG_BT_AUTO_PHY_PERIPHERAL_2M=y
CONFIG_BT_AUTO_PHY_CENTRAL_2M=y
CONFIG_BT_USER_PHY_UPDATE=y

# Connection Subrating for power savings
CONFIG_BT_SUBRATING=y